/*
  File autogenerated by gengetopt version 2.23
  generated with the following command:
  gengetopt --file-name=cmdline 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "cmdline.h"

const char *gengetopt_args_info_purpose = "Simulate TAOS II Occultation Light Curves.\n\nBy sanchezcarlosjr <hello@sanchezcarlosjr.com>";

const char *gengetopt_args_info_usage = "Usage: slc [OPTION]...";

const char *gengetopt_args_info_versiontext = "";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_help[] = {
  "  -h, --help           Print help and exit",
  "  -V, --version        Print version and exit",
  "  -v, --verbose        Produce verbose output  (default=off)",
  "  -o, --output=STRING  Specify output file",
  "  -M, --M=INT          Mesh size in pixels  (default=`2048')",
  "  -l, --lamb=DOUBLE    Wavelength in meters  (default=`6.00e-7')",
  "  -e, --vE=INT         Earth's translation speed in m/s  (default=`29800')",
  "  -r, --vr=INT         Speed of the body if it goes against the direction of\n                         the earth in m/s  (default=`5000')",
  "  -a, --ang=INT        Angle from opposition to calculate the tangential speed\n                         of the object in degrees  (default=`30')",
  "  -f, --fps=INT        Frames per second  (default=`20')",
  "  -m, --mV=INT         Apparent magnitude of the star  (default=`12')",
  "  -n, --nEst=INT       Spectral type selection of the star  (default=`30')",
  "  -N, --nLamb=INT      Number of wavelengths to consider for spectral\n                         calculation  (default=`10')",
  "  -d, --d=INT          Diameter of the object in meters  (default=`3000')",
  "  -u, --ua=DOUBLE      Distance of the object in astronomical units\n                         (default=`45')",
  "  -t, --toffset=INT    Offset in pixels  (default=`0')",
  "  -T, --T=INT          Reading direction in degrees  (default=`0')",
  "  -b, --b=INT          Impact parameter in meters  (default=`0')",
    0
};

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_STRING
  , ARG_INT
  , ARG_DOUBLE
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->verbose_given = 0 ;
  args_info->output_given = 0 ;
  args_info->M_given = 0 ;
  args_info->lamb_given = 0 ;
  args_info->vE_given = 0 ;
  args_info->vr_given = 0 ;
  args_info->ang_given = 0 ;
  args_info->fps_given = 0 ;
  args_info->mV_given = 0 ;
  args_info->nEst_given = 0 ;
  args_info->nLamb_given = 0 ;
  args_info->d_given = 0 ;
  args_info->ua_given = 0 ;
  args_info->toffset_given = 0 ;
  args_info->T_given = 0 ;
  args_info->b_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->verbose_flag = 0;
  args_info->output_arg = NULL;
  args_info->output_orig = NULL;
  args_info->M_arg = 2048;
  args_info->M_orig = NULL;
  args_info->lamb_arg = 6.00e-7;
  args_info->lamb_orig = NULL;
  args_info->vE_arg = 29800;
  args_info->vE_orig = NULL;
  args_info->vr_arg = 5000;
  args_info->vr_orig = NULL;
  args_info->ang_arg = 30;
  args_info->ang_orig = NULL;
  args_info->fps_arg = 20;
  args_info->fps_orig = NULL;
  args_info->mV_arg = 12;
  args_info->mV_orig = NULL;
  args_info->nEst_arg = 30;
  args_info->nEst_orig = NULL;
  args_info->nLamb_arg = 10;
  args_info->nLamb_orig = NULL;
  args_info->d_arg = 3000;
  args_info->d_orig = NULL;
  args_info->ua_arg = 45;
  args_info->ua_orig = NULL;
  args_info->toffset_arg = 0;
  args_info->toffset_orig = NULL;
  args_info->T_arg = 0;
  args_info->T_orig = NULL;
  args_info->b_arg = 0;
  args_info->b_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{


  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->verbose_help = gengetopt_args_info_help[2] ;
  args_info->output_help = gengetopt_args_info_help[3] ;
  args_info->M_help = gengetopt_args_info_help[4] ;
  args_info->lamb_help = gengetopt_args_info_help[5] ;
  args_info->vE_help = gengetopt_args_info_help[6] ;
  args_info->vr_help = gengetopt_args_info_help[7] ;
  args_info->ang_help = gengetopt_args_info_help[8] ;
  args_info->fps_help = gengetopt_args_info_help[9] ;
  args_info->mV_help = gengetopt_args_info_help[10] ;
  args_info->nEst_help = gengetopt_args_info_help[11] ;
  args_info->nLamb_help = gengetopt_args_info_help[12] ;
  args_info->d_help = gengetopt_args_info_help[13] ;
  args_info->ua_help = gengetopt_args_info_help[14] ;
  args_info->toffset_help = gengetopt_args_info_help[15] ;
  args_info->T_help = gengetopt_args_info_help[16] ;
  args_info->b_help = gengetopt_args_info_help[17] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);

  if (strlen(gengetopt_args_info_versiontext) > 0)
    printf("\n%s\n", gengetopt_args_info_versiontext);
}

static void print_help_common(void)
{
	size_t len_purpose = strlen(gengetopt_args_info_purpose);
	size_t len_usage = strlen(gengetopt_args_info_usage);

	if (len_usage > 0) {
		printf("%s\n", gengetopt_args_info_usage);
	}
	if (len_purpose > 0) {
		printf("%s\n", gengetopt_args_info_purpose);
	}

	if (len_usage || len_purpose) {
		printf("\n");
	}

	if (strlen(gengetopt_args_info_description) > 0) {
		printf("%s\n\n", gengetopt_args_info_description);
	}
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{

  free_string_field (&(args_info->output_arg));
  free_string_field (&(args_info->output_orig));
  free_string_field (&(args_info->M_orig));
  free_string_field (&(args_info->lamb_orig));
  free_string_field (&(args_info->vE_orig));
  free_string_field (&(args_info->vr_orig));
  free_string_field (&(args_info->ang_orig));
  free_string_field (&(args_info->fps_orig));
  free_string_field (&(args_info->mV_orig));
  free_string_field (&(args_info->nEst_orig));
  free_string_field (&(args_info->nLamb_orig));
  free_string_field (&(args_info->d_orig));
  free_string_field (&(args_info->ua_orig));
  free_string_field (&(args_info->toffset_orig));
  free_string_field (&(args_info->T_orig));
  free_string_field (&(args_info->b_orig));
  
  

  clear_given (args_info);
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  FIX_UNUSED (values);
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->verbose_given)
    write_into_file(outfile, "verbose", 0, 0 );
  if (args_info->output_given)
    write_into_file(outfile, "output", args_info->output_orig, 0);
  if (args_info->M_given)
    write_into_file(outfile, "M", args_info->M_orig, 0);
  if (args_info->lamb_given)
    write_into_file(outfile, "lamb", args_info->lamb_orig, 0);
  if (args_info->vE_given)
    write_into_file(outfile, "vE", args_info->vE_orig, 0);
  if (args_info->vr_given)
    write_into_file(outfile, "vr", args_info->vr_orig, 0);
  if (args_info->ang_given)
    write_into_file(outfile, "ang", args_info->ang_orig, 0);
  if (args_info->fps_given)
    write_into_file(outfile, "fps", args_info->fps_orig, 0);
  if (args_info->mV_given)
    write_into_file(outfile, "mV", args_info->mV_orig, 0);
  if (args_info->nEst_given)
    write_into_file(outfile, "nEst", args_info->nEst_orig, 0);
  if (args_info->nLamb_given)
    write_into_file(outfile, "nLamb", args_info->nLamb_orig, 0);
  if (args_info->d_given)
    write_into_file(outfile, "d", args_info->d_orig, 0);
  if (args_info->ua_given)
    write_into_file(outfile, "ua", args_info->ua_orig, 0);
  if (args_info->toffset_given)
    write_into_file(outfile, "toffset", args_info->toffset_orig, 0);
  if (args_info->T_given)
    write_into_file(outfile, "T", args_info->T_orig, 0);
  if (args_info->b_given)
    write_into_file(outfile, "b", args_info->b_orig, 0);
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, 0) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error_occurred = 0;
  FIX_UNUSED (additional_error);

  /* checks for required options */
  if (! args_info->output_given)
    {
      fprintf (stderr, "%s: '--output' ('-o') option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  
  
  /* checks for dependences among options */

  return error_occurred;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  FIX_UNUSED (default_value);
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_DOUBLE:
    if (val) *((double *)field) = strtod (val, &stop_char);
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
  case ARG_DOUBLE:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error_occurred = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  /* TODO: Why is this here? It is not used anywhere. */
  override = params->override;
  FIX_UNUSED(override);

  initialize = params->initialize;
  check_required = params->check_required;

  /* TODO: Why is this here? It is not used anywhere. */
  check_ambiguity = params->check_ambiguity;
  FIX_UNUSED(check_ambiguity);

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "verbose",	0, NULL, 'v' },
        { "output",	1, NULL, 'o' },
        { "M",	1, NULL, 'M' },
        { "lamb",	1, NULL, 'l' },
        { "vE",	1, NULL, 'e' },
        { "vr",	1, NULL, 'r' },
        { "ang",	1, NULL, 'a' },
        { "fps",	1, NULL, 'f' },
        { "mV",	1, NULL, 'm' },
        { "nEst",	1, NULL, 'n' },
        { "nLamb",	1, NULL, 'N' },
        { "d",	1, NULL, 'd' },
        { "ua",	1, NULL, 'u' },
        { "toffset",	1, NULL, 't' },
        { "T",	1, NULL, 'T' },
        { "b",	1, NULL, 'b' },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVvo:M:l:e:r:a:f:m:n:N:d:u:t:T:b:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'v':	/* Produce verbose output.  */
        
        
          if (update_arg((void *)&(args_info->verbose_flag), 0, &(args_info->verbose_given),
              &(local_args_info.verbose_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "verbose", 'v',
              additional_error))
            goto failure;
        
          break;
        case 'o':	/* Specify output file.  */
        
        
          if (update_arg( (void *)&(args_info->output_arg), 
               &(args_info->output_orig), &(args_info->output_given),
              &(local_args_info.output_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "output", 'o',
              additional_error))
            goto failure;
        
          break;
        case 'M':	/* Mesh size in pixels.  */
        
        
          if (update_arg( (void *)&(args_info->M_arg), 
               &(args_info->M_orig), &(args_info->M_given),
              &(local_args_info.M_given), optarg, 0, "2048", ARG_INT,
              check_ambiguity, override, 0, 0,
              "M", 'M',
              additional_error))
            goto failure;
        
          break;
        case 'l':	/* Wavelength in meters.  */
        
        
          if (update_arg( (void *)&(args_info->lamb_arg), 
               &(args_info->lamb_orig), &(args_info->lamb_given),
              &(local_args_info.lamb_given), optarg, 0, "6.00e-7", ARG_DOUBLE,
              check_ambiguity, override, 0, 0,
              "lamb", 'l',
              additional_error))
            goto failure;
        
          break;
        case 'e':	/* Earth's translation speed in m/s.  */
        
        
          if (update_arg( (void *)&(args_info->vE_arg), 
               &(args_info->vE_orig), &(args_info->vE_given),
              &(local_args_info.vE_given), optarg, 0, "29800", ARG_INT,
              check_ambiguity, override, 0, 0,
              "vE", 'e',
              additional_error))
            goto failure;
        
          break;
        case 'r':	/* Speed of the body if it goes against the direction of the earth in m/s.  */
        
        
          if (update_arg( (void *)&(args_info->vr_arg), 
               &(args_info->vr_orig), &(args_info->vr_given),
              &(local_args_info.vr_given), optarg, 0, "5000", ARG_INT,
              check_ambiguity, override, 0, 0,
              "vr", 'r',
              additional_error))
            goto failure;
        
          break;
        case 'a':	/* Angle from opposition to calculate the tangential speed of the object in degrees.  */
        
        
          if (update_arg( (void *)&(args_info->ang_arg), 
               &(args_info->ang_orig), &(args_info->ang_given),
              &(local_args_info.ang_given), optarg, 0, "30", ARG_INT,
              check_ambiguity, override, 0, 0,
              "ang", 'a',
              additional_error))
            goto failure;
        
          break;
        case 'f':	/* Frames per second.  */
        
        
          if (update_arg( (void *)&(args_info->fps_arg), 
               &(args_info->fps_orig), &(args_info->fps_given),
              &(local_args_info.fps_given), optarg, 0, "20", ARG_INT,
              check_ambiguity, override, 0, 0,
              "fps", 'f',
              additional_error))
            goto failure;
        
          break;
        case 'm':	/* Apparent magnitude of the star.  */
        
        
          if (update_arg( (void *)&(args_info->mV_arg), 
               &(args_info->mV_orig), &(args_info->mV_given),
              &(local_args_info.mV_given), optarg, 0, "12", ARG_INT,
              check_ambiguity, override, 0, 0,
              "mV", 'm',
              additional_error))
            goto failure;
        
          break;
        case 'n':	/* Spectral type selection of the star.  */
        
        
          if (update_arg( (void *)&(args_info->nEst_arg), 
               &(args_info->nEst_orig), &(args_info->nEst_given),
              &(local_args_info.nEst_given), optarg, 0, "30", ARG_INT,
              check_ambiguity, override, 0, 0,
              "nEst", 'n',
              additional_error))
            goto failure;
        
          break;
        case 'N':	/* Number of wavelengths to consider for spectral calculation.  */
        
        
          if (update_arg( (void *)&(args_info->nLamb_arg), 
               &(args_info->nLamb_orig), &(args_info->nLamb_given),
              &(local_args_info.nLamb_given), optarg, 0, "10", ARG_INT,
              check_ambiguity, override, 0, 0,
              "nLamb", 'N',
              additional_error))
            goto failure;
        
          break;
        case 'd':	/* Diameter of the object in meters.  */
        
        
          if (update_arg( (void *)&(args_info->d_arg), 
               &(args_info->d_orig), &(args_info->d_given),
              &(local_args_info.d_given), optarg, 0, "3000", ARG_INT,
              check_ambiguity, override, 0, 0,
              "d", 'd',
              additional_error))
            goto failure;
        
          break;
        case 'u':	/* Distance of the object in astronomical units.  */
        
        
          if (update_arg( (void *)&(args_info->ua_arg), 
               &(args_info->ua_orig), &(args_info->ua_given),
              &(local_args_info.ua_given), optarg, 0, "45", ARG_DOUBLE,
              check_ambiguity, override, 0, 0,
              "ua", 'u',
              additional_error))
            goto failure;
        
          break;
        case 't':	/* Offset in pixels.  */
        
        
          if (update_arg( (void *)&(args_info->toffset_arg), 
               &(args_info->toffset_orig), &(args_info->toffset_given),
              &(local_args_info.toffset_given), optarg, 0, "0", ARG_INT,
              check_ambiguity, override, 0, 0,
              "toffset", 't',
              additional_error))
            goto failure;
        
          break;
        case 'T':	/* Reading direction in degrees.  */
        
        
          if (update_arg( (void *)&(args_info->T_arg), 
               &(args_info->T_orig), &(args_info->T_given),
              &(local_args_info.T_given), optarg, 0, "0", ARG_INT,
              check_ambiguity, override, 0, 0,
              "T", 'T',
              additional_error))
            goto failure;
        
          break;
        case 'b':	/* Impact parameter in meters.  */
        
        
          if (update_arg( (void *)&(args_info->b_arg), 
               &(args_info->b_orig), &(args_info->b_given),
              &(local_args_info.b_given), optarg, 0, "0", ARG_INT,
              check_ambiguity, override, 0, 0,
              "b", 'b',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */



  if (check_required)
    {
      error_occurred += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error_occurred )
    return (EXIT_FAILURE);

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
/* vim: set ft=c noet ts=8 sts=8 sw=8 tw=80 nojs spell : */
